"""Create a test-only 426-input network; never a walking policy or app asset.

The fixed random network exercises the real exporter and Android inference
path at V20 dimensions without installing an unverified trained candidate.
"""
import hashlib
import json
from pathlib import Path
import tempfile

import numpy as np

from export_onnx import export


def main():
    root = Path(__file__).resolve().parents[1]
    output = root / "app/src/androidTest/assets"
    rng = np.random.default_rng(20426)
    arrays = dict(obs_mean=rng.normal(0., .1, 426).astype(np.float32),
                  obs_var=rng.uniform(.2, 1.2, 426).astype(np.float32))
    for index, inputs in enumerate((426, 128, 128)):
        arrays[f"w{index}"] = rng.normal(0., .04, (128, inputs)).astype(np.float32)
        arrays[f"b{index}"] = rng.normal(0., .01, 128).astype(np.float32)
    arrays["wout"] = rng.normal(0., .04, (12, 128)).astype(np.float32)
    arrays["bout"] = rng.normal(0., .01, 12).astype(np.float32)
    with tempfile.TemporaryDirectory() as temporary:
        folder = Path(temporary)
        weights = folder / "weights.npz"
        np.savez(weights, **arrays)
        metadata = dict(profile_id="test-only-delivery-shape",
                        profile_sha256=hashlib.sha256(b"test-only-delivery-shape").hexdigest(),
                        weights_sha256=hashlib.sha256(weights.read_bytes()).hexdigest(), observation_size=426)
        path = folder / "metadata.json"
        path.write_text(json.dumps(metadata))
        export(weights, path, output / "policy_actor.onnx")
    (output / "README.txt").write_text(
        "TEST FIXTURE ONLY. Random weights, not a trained or deployable robot policy.\n"
        "Generated by tools/create_delivery_onnx_fixture.py, seed 20426.\n"
        "These assets belong only to the instrumentation APK.\n")


if __name__ == "__main__":
    main()
